[deploy]
startCommand = "node simple-working-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 150
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
ENABLE_DOTNET_PARSER = "true"
DOTNET_CV_API_URL = "https://balanced-beauty-production.up.railway.app"
