[deploy]
startCommand = "node src/simple-candidate-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 150
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
ENABLE_DOTNET_PARSER = "true"
